AmauryDBZ/THP_final_project

app/controllers/categories_controller.rb, app/views/projects/index.html.erb, config/routes.rb
Jumbotron on index project is ok, content is for the example.
=> jumbotron with link to new project is done

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/projects_controller.rb, app/views/projects/new.html.erb, config/application.rb, config/initializers/routes_translator.rb, config/locales/devise.fr.yml, config/routes.rb
=> updated roads in french

app/views/projects/index.html.erb
Please check code for convention : 
line 105 : <%= project.user.first_name + ' ' + project.user.last_name  %>
line 110 : <%= project.created_at.strftime('%d/%m/%Y')  %>
We can change line 105 when user controller is created
=> index page cards are ok and links redirect to show project

app/controllers/projects_controller.rb, app/views/projects/index.html.erb, app/views/projects/new.html.erb, config/routes.rb
Form for new project is a MVP. 
Little changes to routes. 
If user has first and last name, show it in cards on index projects.
The project create itself without validation from admin. 
Must be log to create project.
=> creation of project is done without validation of admin

app/controllers/application_controller.rb, app/views/devise/registrations/edit.html.erb
update devise views with all needed inputs
=> update devise views with all needed inputs

app/assets/javascripts/admin.coffee, app/assets/javascripts/admin/projects.coffee, app/assets/stylesheets/admin.scss, app/assets/stylesheets/admin/projects.scss, app/controllers/admin/projects_controller.rb, app/controllers/admin_controller.rb, app/controllers/projects_controller.rb, app/helpers/admin/projects_helper.rb, app/helpers/admin_helper.rb, app/views/admin/index.html.erb, app/views/admin/projects/index.html.erb, config/locales/devise.fr.yml, config/routes.rb, db/migrate/20200906123909_add_validated_to_project.rb, db/schema.rb, spec/helpers/admin/projects_helper_spec.rb, spec/helpers/admin_helper_spec.rb, spec/requests/admin/projects_request_spec.rb, spec/requests/admin_request_spec.rb
Controllers admin are created. Migration add 'validated' to table Projects. URLs and routes are translated for admin. Authentification for admin is done. Admin can access the dashboard and the index with projects waiting to be validated. Project show is not yet build.
=> Admin dashboard and admin on project

app/controllers/application_controller.rb, app/views/devise/registrations/edit.html.erb, app/views/projects/index.html.erb, app/views/users/_personnal_informations.html.erb, app/views/users/_public_informations.html.erb
update index with condition for show projects only after  admins validations
=> update index with condition 

app/views/layouts/_navbar.html.erb
update navbar link with link to for project creation if user_signed_in
=> update navbar link with link to for project creation if user_signed_in

app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, config/environment.rb, config/environments/development.rb, config/environments/production.rb, config/initializers/devise.rb, db/seeds.rb
Translate all devise mailer and configure mailer for development and production
=> Translate all devise mailer and configure mailer 

app/views/admin/index.html.erb, app/views/admin/projects/index.html.erb, app/views/users/_personnal_informations.html.erb, app/views/users/_public_informations.html.erb
Updated to only show the part that lists projects if it is not empty
=> Updated to only show the part that lists projects if it is not empty

app/views/projects/_new_project_form.html.erb
=> New project form fixed

app/views/projects/_edit_project_form.html.erb
=> fixed edit form

app/views/projects/show.html.erb
display licence card only if licence on project are not NIL
=> display licence card only if licence on project are not NIL

app/views/users/_bank_informations_reminder.html.erb
redesign on bank information reminder partial
=> redesign on bank information reminder partial

app/views/admin/index.html.erb, config/environments/production.rb
Align all buttons on the same lines in admin index view
=> Admin on project

app/controllers/admin/projects_controller.rb, app/controllers/projects_controller.rb
delete project also in donations table
=> delete project also in donations table

app/assets/stylesheets/main.css, app/controllers/bank_details_controller.rb, app/controllers/users_controller.rb, app/helpers/bank_details_helper.rb, app/views/bank_details/edit.html.erb, app/views/bank_details/new.html.erb, app/views/bank_details/show.html.erb, app/views/users/_personal_informations.html.erb, app/views/users/_public_informations.html.erb, config/environments/development.rb, config/routes.rb
edit and show bank details ok for admin and users with authentification checkings
=> Edit bank details

app/controllers/categories_controller.rb, app/views/categories/show.html.erb, db/migrate/20200910100003_add_description_to_categories.rb, db/schema.rb, db/seeds.rb
Added projects in categories show
=> Add categories

app/views/layouts/_footer.html.erb
Added categories link in footer
=> Added categories link in footer

app/views/projects/index.html.erb
Fixed responsivity for buttons on top index page
=> Fixed responsivity for buttons on top index page

app/controllers/projects_controller.rb, app/views/categories/show.html.erb, app/views/projects/_all_projects.html.erb, app/views/projects/_most_supported.html.erb, app/views/projects/_most_visited.html.erb, app/views/projects/_new_projects.html.erb, app/views/projects/index.html.erb
Reviews of the index front, and categories navigation added
=> Index updates

db/seeds.rb
Pictures resized & compressed and stored in raspberry pi.
=> update category images

README.md, app/assets/javascripts/application.js, app/helpers/users_helper.rb, app/views/admin/projects/_edit.html.erb, app/views/projects/_few_figures.html.erb
sentences remade in finance card
=> Show project

app/views/layouts/_navbar.html.erb
updated navbar for case of user are connected or not
=> updated navbar for case of user are connected or not

app/views/layouts/_footer.html.erb
Updated footer link in case of user are signed in or not
=> Updated footer link in case of user are signed in or not

app/controllers/bank_details_controller.rb
=> Encrypt bank details

app/views/devise/shared/_devisemes.html.erb, app/views/layouts/_flash.html.erb
Fixed alerts in signed in page
=> Fixed alerts in signed in page

app/views/layouts/_navbar.html.erb
=> manifest_button changed

app/views/projects/_new_project_form.html.erb, db/schema.rb
fixed text on the left following the recommendation of felix
=> fixed text on the left following the recommendation of felix

app/views/users/_public_informations.html.erb, db/schema.rb
fixed public show for display project only if project are validated
=> fixed public show for display project only if project are validated

app/views/devise/registrations/edit.html.erb
updated edit registration view
=> updated edit registration view

app/views/landing_pages/index.html.erb
updated right button with primary color and same size
=> updated right button with primary color and same size

app/controllers/projects_controller.rb
add condition for update categories in project controller
=> add condition for update categories in project controller

app/views/bank_details/edit.html.erb, app/views/bank_details/show.html.erb
updated edit and show views for bankdetails
=> updated edit and show views for bankdetails
